jobs:
  add-assignee:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: kentaro-m/auto-assign-action@248761c4feb3917c1b0444e33fad1a50093b9847
name: Auto Assign
on:
  repository_dispatch:
    types: trigger-ga___auto-assign.yml
