jobs:
  check-pr-title:
    name: Check PR Title
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        submodules: false
    - continue-on-error: true
      name: Enforce PR title
      uses: realm/ci-actions/title-checker@main
      with:
        error-hint: Invalid PR title. Make sure it's prefixed with the JIRA ticket
          the PR addresses or add the no-jira-ticket label.
        ignore-labels: no-jira-ticket
        regex: R[A-Z]{2,6}-[0-9]{1,6}
name: Check PR Title
on:
  repository_dispatch:
    types: trigger-ga___check-pr-title.yml
