jobs:
  changelog:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@8230315d06ad95c617244d2f265d237a1682d445
      with:
        submodules: false
    - continue-on-error: true
      name: Enforce Changelog
      uses: dangoslen/changelog-enforcer@c0b9fd225180a405c5f21f7a74b99e2eccc3e951
      with:
        missingUpdateErrorMessage: Please add an entry in CHANGELOG.md or apply the
          'no-changelog' label to skip this check.
        skipLabels: no-changelog
name: Check Changelog
on:
  repository_dispatch:
    types: trigger-ga___check-changelog.yml
