jobs:
  label-issues-policy:
    permissions:
      issues: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      id: issue-parser
      name: Parse issue form
      uses: stefanbuck/github-issue-parser@c1a559d78bfb8dd05216dab9ffd2b91082ff5324
      with:
        template-path: .github/ISSUE_TEMPLATE/${{ matrix.template }}
    - continue-on-error: true
      name: Set labels based on policy
      uses: redhat-plumbers-in-action/advanced-issue-labeler@6ee6fddfd744ee26b977e6a0436916f256896971
      with:
        issue-form: ${{ steps.issue-parser.outputs.jsonString }}
        template: ${{ matrix.template }}
        token: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      matrix:
        template:
        - bug.yml
        - feature.yml
name: Issue labeler (policy)
on:
  repository_dispatch:
    types: trigger-ga___issue-labeler.yml
