concurrency:
  group: lock-threads
jobs:
  action:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: dessant/lock-threads@v5
      with:
        issue-inactive-days: 30
        log-output: true
        pr-inactive-days: 30
name: Lock Threads
on:
  repository_dispatch:
    types: trigger-ga___lock-threads.yml
permissions:
  discussions: write
  issues: write
  pull-requests: write
